name: Keycloak Nightly
on:
  push:
    branches:
      - KEYCLOAK-11468
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'


env:
  # workaround for Maven >= 3.8.1 (see KEYCLOAK-17812)
  MVN_MIRRORS: '[{ "id": "jboss-public-repository-group-https", "mirrorOf": "jboss-public-repository-group", "url": "https://repository.jboss.org/nexus/content/groups/public/" }]'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: whelk-io/maven-settings-xml-action@v15
        with:
          mirrors: ${{ env.MVN_MIRRORS }}
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Build Keycloak
        run: |
           mvn clean install -e -DskipTests -Pdistribution -pl distribution/server-dist -am

      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v2
        with:
          name: keycloak-artifacts-.zip
          retention-days: 2
          path: |
            distribution/server-dist/target/keycloak-*.tar.gz

      - name: Remove keycloak artifacts before caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm -rf ~/.m2/repository/org/keycloak